// Sample/demo content shown when the backend cannot be reached, so the
// public browsing experience still looks and feels real instead of empty
// or broken. Never used for authenticated/personal data (bookings,
// payments, dashboards) — only for public listings anyone could see.
import { PropertyResponse, PopularLocation } from "../../api";

export const MOCK_GOVERNORATES: string[] = [
  "Alexandria",
  "Matrouh",
  "North Coast",
  "Red Sea",
];

const now = new Date().toISOString();

// Mock property ids start at 900000 so they can never collide with a real
// backend id, which lets the UI tell "sample" listings apart from real ones.
export const MOCK_PROPERTIES: PropertyResponse[] = [
  {
    propertyId: 900001,
    ownerId: 0,
    titleAr: "فيلا فاخرة على الشاطئ - مراسي",
    titleEn: "Luxury Beachfront Villa - Marassi",
    descriptionAr: "فيلا مطلة على البحر مباشرة مع مسبح خاص وحديقة واسعة.",
    descriptionEn:
      "Stunning beachfront villa with a private pool and spacious garden, steps from the sea.",
    propertyType: "villa",
    rentalType: "entire_place",
    governorate: "North Coast",
    city: "Marassi",
    bedrooms: 4,
    bathrooms: 3,
    guestsCapacity: 8,
    furnished: true,
    petsAllowed: false,
    pricePerNight: 8500,
    currency: "EGP",
    status: "active",
    isVerified: true,
    averageRating: 4.9,
    totalReviews: 128,
    isFeatured: true,
    coverImage:
      "https://images.unsplash.com/photo-1678788762802-0c6c6cdd89fe?w=800&q=80",
    createdAt: now,
    updatedAt: now,
  },
  {
    propertyId: 900002,
    ownerId: 0,
    titleAr: "شاليه عصري - سيدي عبد الرحمن",
    titleEn: "Modern Chalet - Sidi Abdel Rahman",
    descriptionAr: "شاليه أنيق قريب من الشاطئ يتسع لعائلة صغيرة.",
    descriptionEn:
      "Stylish chalet close to the beach, perfect for a small family getaway.",
    propertyType: "chalet",
    rentalType: "entire_place",
    governorate: "Matrouh",
    city: "Sidi Abdel Rahman",
    bedrooms: 2,
    bathrooms: 2,
    guestsCapacity: 5,
    furnished: true,
    petsAllowed: true,
    pricePerNight: 4200,
    currency: "EGP",
    status: "active",
    isVerified: true,
    averageRating: 4.7,
    totalReviews: 64,
    isFeatured: true,
    coverImage:
      "https://images.unsplash.com/photo-1593663094448-9ea85c6e8456?w=800&q=80",
    createdAt: now,
    updatedAt: now,
  },
  {
    propertyId: 900003,
    ownerId: 0,
    titleAr: "شقة إطلالة بحرية - العلمين الجديدة",
    titleEn: "Sea View Apartment - New Alamein",
    descriptionAr: "شقة مريحة بإطلالة مباشرة على البحر المتوسط.",
    descriptionEn:
      "Comfortable apartment with a direct view of the Mediterranean Sea.",
    propertyType: "apartment",
    rentalType: "entire_place",
    governorate: "North Coast",
    city: "New Alamein",
    bedrooms: 3,
    bathrooms: 2,
    guestsCapacity: 6,
    furnished: true,
    petsAllowed: false,
    pricePerNight: 3500,
    currency: "EGP",
    status: "active",
    isVerified: true,
    averageRating: 4.6,
    totalReviews: 41,
    isFeatured: true,
    coverImage:
      "https://images.unsplash.com/photo-1700126689261-1f5bdfe5adcc?w=800&q=80",
    createdAt: now,
    updatedAt: now,
  },
  {
    propertyId: 900004,
    ownerId: 0,
    titleAr: "منتجع هادئ - العين السخنة",
    titleEn: "Tranquil Resort Villa - Ain Sokhna",
    descriptionAr: "فيلا هادئة داخل منتجع مغلق بالقرب من البحر الأحمر.",
    descriptionEn:
      "Peaceful villa inside a gated resort just minutes from the Red Sea.",
    propertyType: "villa",
    rentalType: "entire_place",
    governorate: "Red Sea",
    city: "Ain Sokhna",
    bedrooms: 3,
    bathrooms: 3,
    guestsCapacity: 7,
    furnished: true,
    petsAllowed: false,
    pricePerNight: 5200,
    currency: "EGP",
    status: "active",
    isVerified: true,
    averageRating: 4.8,
    totalReviews: 87,
    isFeatured: true,
    coverImage:
      "https://images.unsplash.com/photo-1729720281771-b790dfb6ec7f?w=800&q=80",
    createdAt: now,
    updatedAt: now,
  },
  {
    propertyId: 900005,
    ownerId: 0,
    titleAr: "استوديو مطل على المارينا",
    titleEn: "Marina View Studio",
    descriptionAr: "استوديو أنيق يطل على المارينا، مثالي للأزواج.",
    descriptionEn:
      "Chic studio overlooking the marina, ideal for a couple's getaway.",
    propertyType: "apartment",
    rentalType: "entire_place",
    governorate: "Matrouh",
    city: "Marina",
    bedrooms: 1,
    bathrooms: 1,
    guestsCapacity: 2,
    furnished: true,
    petsAllowed: false,
    pricePerNight: 2400,
    currency: "EGP",
    status: "active",
    isVerified: true,
    averageRating: 4.5,
    totalReviews: 33,
    isFeatured: false,
    coverImage:
      "https://images.unsplash.com/photo-1629359080404-2dafcfd9f159?w=800&q=80",
    createdAt: now,
    updatedAt: now,
  },
  {
    propertyId: 900006,
    ownerId: 0,
    titleAr: "فيلا عائلية كبيرة - الجونة",
    titleEn: "Spacious Family Villa - El Gouna",
    descriptionAr: "فيلا واسعة مع حديقة ومسبح، تناسب التجمعات العائلية.",
    descriptionEn:
      "Roomy villa with a garden and pool, great for family gatherings.",
    propertyType: "villa",
    rentalType: "entire_place",
    governorate: "Red Sea",
    city: "El Gouna",
    bedrooms: 5,
    bathrooms: 4,
    guestsCapacity: 10,
    furnished: true,
    petsAllowed: true,
    pricePerNight: 9800,
    currency: "EGP",
    status: "active",
    isVerified: true,
    averageRating: 4.9,
    totalReviews: 156,
    isFeatured: true,
    coverImage:
      "https://images.unsplash.com/photo-1638310081327-5b4b5da6d155?w=800&q=80",
    createdAt: now,
    updatedAt: now,
  },
  {
    propertyId: 900007,
    ownerId: 0,
    titleAr: "شقة عصرية - كورنيش الإسكندرية",
    titleEn: "Modern Apartment - Alexandria Corniche",
    descriptionAr: "شقة عصرية على كورنيش الإسكندرية بإطلالة رائعة.",
    descriptionEn:
      "Modern apartment right on the Alexandria Corniche with a lovely view.",
    propertyType: "apartment",
    rentalType: "entire_place",
    governorate: "Alexandria",
    city: "Miami",
    bedrooms: 2,
    bathrooms: 1,
    guestsCapacity: 4,
    furnished: true,
    petsAllowed: false,
    pricePerNight: 2100,
    currency: "EGP",
    status: "active",
    isVerified: true,
    averageRating: 4.4,
    totalReviews: 29,
    isFeatured: false,
    coverImage:
      "https://images.unsplash.com/photo-1700126689261-1f5bdfe5adcc?w=800&q=80",
    createdAt: now,
    updatedAt: now,
  },
  {
    propertyId: 900008,
    ownerId: 0,
    titleAr: "شاليه بمسبح خاص - هاسيندا باي",
    titleEn: "Private Pool Chalet - Hacienda Bay",
    descriptionAr: "شاليه مريح مع مسبح خاص على بعد خطوات من الشاطئ.",
    descriptionEn:
      "Cozy chalet with a private pool just steps from the beach.",
    propertyType: "chalet",
    rentalType: "entire_place",
    governorate: "North Coast",
    city: "Hacienda Bay",
    bedrooms: 3,
    bathrooms: 2,
    guestsCapacity: 6,
    furnished: true,
    petsAllowed: false,
    pricePerNight: 6300,
    currency: "EGP",
    status: "active",
    isVerified: true,
    averageRating: 4.7,
    totalReviews: 52,
    isFeatured: true,
    coverImage:
      "https://images.unsplash.com/photo-1593663094448-9ea85c6e8456?w=800&q=80",
    createdAt: now,
    updatedAt: now,
  },
];

export const MOCK_POPULAR_LOCATIONS: PopularLocation[] = [
  {
    governorate: "North Coast",
    city: "Marassi",
    propertyCount: 42,
    averagePrice: 6800,
    minPrice: 3500,
    maxPrice: 9800,
    totalViews: 0,
  },
  {
    governorate: "Red Sea",
    city: "El Gouna",
    propertyCount: 35,
    averagePrice: 5900,
    minPrice: 2400,
    maxPrice: 9800,
    totalViews: 0,
  },
  {
    governorate: "Matrouh",
    city: "Sidi Abdel Rahman",
    propertyCount: 28,
    averagePrice: 4200,
    minPrice: 2100,
    maxPrice: 8500,
    totalViews: 0,
  },
];

export function getMockPropertyById(id: number): PropertyResponse {
  return (
    MOCK_PROPERTIES.find((property) => property.propertyId === id) ||
    MOCK_PROPERTIES[0]
  );
}

export function isMockPropertyId(id: number): boolean {
  return id >= 900000;
}
